name: Deploy .NET App to IIS

on:
  workflow_dispatch:

jobs:
  build_project:
    runs-on: self-hosted
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Publish .NET Project
        run: dotnet publish WebApplication2/WebApplication1.csproj -c Release -o ./publish

  build_failed_branch:
    runs-on: self-hosted
    needs: build_project

    if: failure()
    steps:
      - name: Notify build failed
        run: "Build failed!!"
  run_tests:
    runs-on: self-hosted
    needs: build_project

    steps:
      # ✅ Run Playwright tests
      - name: Run Playwright tests
        run: dotnet test WebApplication1.Test/WebApplication1.Test.csproj

      - name: Install Playwright and Browsers
        run: |
          cd WebApplication1
          dotnet add package Microsoft.Playwright
          dotnet build
          playwright install
  deploy_iis:
    runs-on: self-hosted
    needs: run_tests

    steps:
      - name: Stop Website 'mywebsite'
        shell: cmd
        run: |
          set PATH=%PATH%;C:\Windows\System32\inetsrv
          appcmd stop site /site.name:"mywebsite"

      - name: Deploy to IIS
        shell: cmd
        run: |
          set destination=D:\myapplication
          if exist %destination% (
            del /q /s %destination%\*
          ) else (
            mkdir %destination%
          )
          xcopy .\publish\* %destination% /s /e /y

      - name: Start Website 'mywebsite'
        shell: cmd
        run: |
          set PATH=%PATH%;C:\Windows\System32\inetsrv
          appcmd start site /site.name:"mywebsite"
