name: Deploy .NET App to IIS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Uncomment if needed
      # - name: Setup .NET SDK
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '8.0.x'

      # - name: Restore Dependencies
      #   run: dotnet restore WebApplication1/WebApplication1.csproj

      - name: Publish .NET Project
        run: dotnet publish WebApplication1/WebApplication1.csproj -c Release -o ./publish

      - name: Stop Website 'mywebsite'
        shell: cmd
        run: |
          set PATH=%PATH%;C:\Windows\System32\inetsrv
          runas /user:Administrator "net stop W3SVC"
          runas /user:Administrator "appcmd stop site /site.name:'mywebsite'"

      - name: Deploy to IIS
        shell: cmd
        run: |
          set destination=D:\myapplication
          if exist %destination% (
            del /q /s %destination%\*
          ) else (
            mkdir %destination%
          )
          xcopy .\publish\* %destination% /s /e /y

      - name: Start Website 'mywebsite'
        shell: cmd
        run: |
          set PATH=%PATH%;C:\Windows\System32\inetsrv
          runas /user:Administrator "appcmd start site /site.name:'mywebsite'"
          runas /user:Administrator "net start W3SVC"
